# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y3kVQ4ohFCvVZk-moPKMjR6jk6ARr1RS
"""

jugador = {}

jugador ["Nombre"] = input ("Nombre del jugador?")
jugador ["Apellido"] = input ("apellido del jugador/?")
jugador ["Edad"] = int (input("Edad del jugador?"))
jugador ["Precio"] = float (input ("Precio del jugador?"))

for clave in jugador:
    print (f"{clave} : {jugador[clave]}")